data:
    # path to the dataset folder that you want to put the training data under the build_dataset folder
    target_path: #absolute path recommended
    splits:
        train: 0.7
        valid: 0.15
        test: 0.15